config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'pages/list'
  root 'pages#index'

  get '/list', to:'pages#list'

  resources :netflix_titles, only: [:index, :show] do
    collection do
      get 'filter'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/netflix_title.rb
class NetflixTitle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  rescue_from ActiveRecord::RecordNotFound, with: :render_not_found

  private

  def render_not_found
    render json: { error: 'Not Found' }, status: :not_found
  end
end

app/controllers/netflix_titles_controller.rb
class NetflixTitlesController < ApplicationController
  before_action :set_netflix_title, only: [:show]

  def index
    @netflix_titles = NetflixTitle.order(year: :asc)
    render json: @netflix_titles
  end

  def filter
    @netflix_titles = NetflixTitleFilter.new(params).filter
    render json: @netflix_titles
  end

  def show
    render json: @netflix_title
  end

  private

  def set_netflix_title
    @netflix_title = NetflixTitle.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    # Nenhuma lógica necessária para a página inicial por enquanto
  end

  # @return [nil]
  def list
    @netflix_titles = NetflixTitle.order(year: :asc)
    render 'list'
  end
end

app/views/pages/index.html.erb
<h1>Welcome to Netflix Titles!</h1>
<%= link_to 'List Titles', list_path, class: 'btn btn-primary' %>

app/views/pages/list.html.erb
<h1>Netflix Titles List</h1>
<div class="container">
  <table class="table">
    <thead>
    <tr>
      <th>Title</th>
      <th>Genre</th>
      <th>Year</th>
      <th>Country</th>
      <th>Published At</th>
      <th>Description</th>
    </tr>
    </thead>
    <tbody>
    <% @netflix_titles.each do |title| %>
      <tr>
        <td><%= title.title %></td>
        <td><%= title.genre %></td>
        <td><%= title.year %></td>
        <td><%= title.country %></td>
        <td><%= title.published_at %></td>
        <td><%= title.description %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Back to Home', root_path, class: 'btn btn-primary' %>